# Generated by Django 6.0.5 on 2026-08-07 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0004_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
